name: pgpatrol
description: A minimalist, PostgreSQL monitoring application built with Flutter and Dart.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  postgres: ^2.6.3
  syncfusion_flutter_charts: ^29.1.35
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  vector_math: ^2.1.4
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/ 
    - assets/images/
